// Importación de hojas de estilo globales y de react-toastify
import './globals.css';
import 'react-toastify/dist/ReactToastify.css';

// Importación de la fuente Inter de Google Fonts
import { Inter } from 'next/font/google';

// Importación de componentes y contextos personalizados
import Providers from './providers';
import { Navbar } from './components';
import { InternetContextProvider } from './context';

// Carga de la fuente Inter con subconjuntos específicos
const inter = Inter({ subsets: ['latin'] });

// Metadatos para el manifiesto y la descripción de la aplicación
export const metadata = {
  manifest: '/manifest.json',
  title: 'Create Next App',
  description: 'Generated by create next app'
};

// Componente RootLayout que define la estructura base de la aplicación
export default function RootLayout({ children }) {
  return (
    // Establece el idioma de la aplicación como español
    <html lang='es'>
    <body className={inter.className}>
    {/* Envuelve los elementos de la aplicación con los proveedores de contexto */}
    <Providers>
      {/* Componente Navbar para la navegación */}
      <Navbar />
      {/* Contenedor principal para el contenido de la aplicación */}
      <main>
        {/* Proveedor del contexto de Internet para envolver el contenido */}
        <InternetContextProvider>{children}</InternetContextProvider>
      </main>
      {/* Footer vacío que puede ser utilizado para agregar contenido adicional */}
      <footer></footer>
    </Providers>
    </body>
    </html>
  );
}
